### ISSUE TITLE
GitHub workshop TODO list

### ISSUE THREAD

**Issue by BatoolMM** [ARab-R/ARab_R#21]
- [x] Announcement in Website
- [x] Announcement in social media
- [x] Complete the materials
- [x] Prepare the poll
- [x] Add it to Zenodo
- [x]  Collect feedback

**Comment by BatoolMM** [comment]
Done!
https://zenodo.org/record/6484771#.Yp-5dhNue3I
